#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	conf.env.append_unique('DEFINES', ['BENCHMARK','VGUIMATSURFACE_DLL_EXPORT','GAMEUI_EXPORTS','ENABLE_CHROMEHTMLWINDOW'])
	if conf.env.DEST_OS == 'win32':
		conf.env.append_unique('DEFINES', ['fopen=dont_use_fopen'])
 
def build(bld):
	sources = [
		File	(['Clip2D.cpp']),
		File	(['Cursor.cpp']),
		File	(['../public/filesystem_helpers.cpp']),
		File	(['Input.cpp']),
		File	(['MatSystemSurface.cpp']),
		File	(['memorybitmap.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['../vgui2/src/htmlwindow.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['../vgui2/src/vgui_key_translation.cpp']),
		File	(['../public/vgui_controls/vgui_controls.cpp']),
		File	(['../public/tier0/memoverride.cpp'])
	]

	includes = [
		'../thirdparty/freetype/include',
		'../thirdparty/fontconfig'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'tier3',
		'interfaces',
		'vstdlib',
		'bitmap',
		'mathlib',
		'vgui_controls',
		'vgui_surfacelib',
		'dmxloader',
		'freetype',
		'fontconfig',
		'expat'
	]

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.shlib(
		target   = 'vguimatsurface',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		install_path = bld.env.BINDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
