#!/usr/bin/env python
# modified from FWGS/xash3d-fwgs

from waflib import Build, ConfigSet, Context, Logs
import sys, os, optparse

default_prefix = '../game'

PROJECTS = [
	'tier0',
	'tier1',
	'tier2',
	'tier3',
	'togl',
	'interfaces',
	'vstdlib',
	'mathlib',
	'mathlib/extended',
	'appframework',
	'bitmap',
	'bonesetup',
	'dmxloader',
	'soundsystem/lowlevel',
	'steam',
	'vgui2/matsys_controls',
	'vgui2/vgui_controls',
	'videocfg',
	'vpklib',
	'vtf',
	'launcher_main',
	'launcher',
	'engine',
	'engine/voice_codecs/minimp3',
	'filesystem',
	'inputsystem',
	'vphysics',
	'materialsystem',
	'datacache',
	'studiorender',
	'soundemittersystem',
	'vscript',
	'thirdparty/joltphysics',
	'thirdparty/jpeg-9e',
	'thirdparty/openal-soft',
	'thirdparty/protobuf-2.5.0',
	'thirdparty/quickhull',
	'thirdparty/SDL2',
	'utils/bzip2'
]

def options(opt):
	opt.load('compiler_c compiler_cxx')

	grp = opt.add_option_group('Common options')

	grp.add_option('--dedicated', action = 'store_true', dest = 'DEDICATED', default = False,
		help = 'build dedicated server(WIP) [default: %default]')

	grp.add_option('--togl', action = 'store_true', dest = 'TOGL', default = True,
		help = 'build ToGL [default: %default]')

	grp.add_option('--64bits', action = 'store_true', dest = 'PLATFORM_64BITS', default = True,
		help = 'build for 64bits platform [default: %default]')

	grp.add_option('--silence', action = 'store_true', dest = 'SILENCE', default = False,
		help = 'build in silence [default: %default]')

	grp.add_option('--cfg', action = 'store', dest = 'CFG', default = 'release',
		help = 'build types [default: %default]')

	grp.add_option('--ccache', action = 'store_true', dest = 'CCACHE', default = False,
		help = 'build with ccache [default: %default]')

	grp.add_option('--strip', action = 'store_true', dest = 'STRIP', default = False,
		help = 'strip libs\' additional info [default: %default]')

	grp.add_option('--ndk', action = 'store_true', dest = 'NDK', default = False,
		help = 'build with android ndk [default: %default]')

def configure(conf):
	conf.load('compiler_c compiler_cxx')

	if conf.options.NDK:
		conf.env.DEST_OS = 'linux'

	if conf.options.CCACHE:
		conf.find_program('ccache', var='CCACHE')
	if conf.options.STRIP:
		conf.find_program('strip', var='STRIP')

	defines = ['CSTRIKE_REL_BUILD=1','RAD_TELEMETRY_DISABLED','CSTRIKE15','VERSION_SAFE_STEAM_API_INTERFACES']

	if conf.env.DEST_OS in 'linux':
		cflags = ['-fPIC','-pthread']
		cxxflags = ['-std=c++17']
		linkflags = ['-Wl,--no-undefined','-pthread','-ldl','-no-canonical-prefixes','-Wl,--no-warn-mismatch']
		flags = ['-fvisibility=hidden']
		march = []
		defines += ['GNUC','_DLL_EXT=.so','_LINUX','LINUX','_POSIX','POSIX','DX_TO_GL_ABSTRACTION','USE_SDL','GL_GLEXT_PROTOTYPES','AL_ALEXT_PROTOTYPES']
		if not conf.options.SILENCE:
			warnings = ['-Wall']
		else:
			warnings = ['-w']

		if conf.options.NDK:
			if 'ANDROID_NDK' in os.environ:
				ndk_path = os.environ.get('ANDROID_NDK')
			else:
				conf.fatal('Set ANDROID_NDK environment variable pointing to the root of Android NDK!')
			if conf.options.PLATFORM_64BITS:
				conf.env.DEST_CPU = 'aarch64'
				conf.env.CC    = conf.env.LINK_CC  = [ndk_path + '/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang']
				conf.env.CXX   = conf.env.LINK_CXX = [ndk_path + '/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++']
				conf.env.AR    = [ndk_path + '/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar']
				conf.env.STRIP = [ndk_path + '/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip']
				conf.env.CC_NAME = conf.env.COMPILER_CC = 'clang'
				conf.env.COMPILER_CXX = 'clang++'
				cxxflags += ['-I' + ndk_path + '/sources/cxx-stl/llvm-libc++/include']
				linkflags += ['-lc++abi','-lc++_static','-fuse-ld=lld']
			else:
				conf.fatal('Doesn\'t support 32-bits, use --64bits!')
			defines += ['ANDROID']
			conf.get_cc_version(conf.env.CXX, clang=True)
			conf.check(lib='android', uselib_store='ANDROID')
			conf.check(lib='log', uselib_store='LOG')
			conf.check(lib='GLESv1_CM', uselib_store='GLESV1_CM')
			conf.check(lib='GLESv2', uselib_store='GLESV2')
		else:
			conf.check(lib='SDL2', uselib_store='SDL2')
			conf.check(lib='curl', uselib_store='curl')
		conf.check(lib='z', uselib_store='zlib')

		if conf.env.DEST_CPU in ['arm','aarch64']:
			cflags += ['-fsigned-char']

		if conf.env.CC_NAME == 'gcc':
			warnings += ['-fdiagnostics-color=always']
			defines += ['COMPILER_GCC']
		elif conf.env.CC_NAME == 'clang':
			warnings += ['-fcolor-diagnostics']
			defines += ['COMPILER_CLANG']

		if conf.env.CC_NAME == 'clang' and conf.options.CFG == 'asan':
			linkflags += ['-Wl,--unresolved-symbols=ignore-all']

		if conf.env.CC_NAME == 'clang':
			cxxflags += ['-stdlib=libstdc++']

		if conf.options.CFG == 'debug':
			cflags += ['-O0','-g3']
			cxxflags += ['-O0','-g3']
		elif conf.options.CFG == 'release':
			cflags += ['-O3']
			cxxflags += ['-O3']
		elif conf.options.CFG == 'asan':
			cflags += ['-O0','-g','-fsanitize=address']
			cxxflags += ['-O0','-g','-fsanitize=address']
			linkflags += ['-fsanitize=address']
		else:
			conf.fatal('cfg not found')

		defines += ['NDEBUG=1']

		if conf.options.PLATFORM_64BITS:
			march += ['-m64']
			if conf.env.DEST_CPU == 'x86_64':
				march += ['-march=nocona','-mtune=core2','-mfpmath=sse']
			elif conf.env.DEST_CPU in ['arm','aarch64']:
				march += ['-march=armv8-a','-mtune=cortex-a53','-mcpu=cortex-a53']
			defines += ['PLATFORM_64BITS']
		elif conf.env.DEST_CPU in ['x86','x86_64'] and not conf.options.PLATFORM_64BITS:
			march += ['-m32']
			if conf.env.DEST_CPU == 'x86_64':
				march += ['-march=prescott','-mtune=core2','-mfpmath=sse']
			elif conf.env.DEST_CPU == 'arm':
				march += ['-march=armv7-a','-mtune=cortex-a15','-mcpu=cortex-a15','-mfpu=neon','-mfloat-abi=hard','-mthumb','-mvectorize-with-neon-quad']

		if conf.options.DEDICATED:
			defines += [
				'DEDICATED'
			]

		conf.env.append_unique('CFLAGS', march + cflags + warnings + flags)
		conf.env.append_unique('CXXFLAGS', march + cflags + cxxflags + warnings + flags)
		conf.env.append_unique('LINKFLAGS', march + linkflags + flags)
		conf.env.append_unique('DEFINES', defines)

	includes = [
		os.path.abspath('common'),
		os.path.abspath('public'),
		os.path.abspath('public/tier0'),
		os.path.abspath('public/tier1'),
		os.path.abspath('thirdparty/SDL2/include'),
		os.path.abspath('thirdparty/openal-soft/include')
	]
	conf.env.append_unique('INCLUDES', includes)

	if conf.options.CCACHE:
		conf.env.CC = conf.env.CCACHE + conf.env.CC
		conf.env.CXX = conf.env.CCACHE + conf.env.CXX

	conf.check_cc(cflags=cflags, linkflags=linkflags, msg='Checking for required C flags')
	conf.check_cxx(cxxflags=cxxflags, linkflags=linkflags, msg='Checking for required C++ flags')

	store_path = os.path.join(conf.bldnode.abspath(), 'options.py')
	store_data = ConfigSet.ConfigSet()
	options = vars(conf.options)
	store_data['OPTIONS'] = vars(conf.options)
	store_data.store(store_path)

	for name in PROJECTS:	
		depth_push(name)
		saveenv = conf.env
		conf.setenv(name, conf.env)
		conf.env.ENVNAME = name
		conf.recurse(name)
		conf.setenv('')
		conf.env = saveenv
		depth_pop()

DEPTH = ''
def depth_push(path):
	global DEPTH
	DEPTH = os.path.join(DEPTH, path)
def depth_pop():
	global DEPTH
	DEPTH = os.path.dirname(DEPTH)

def copy_fun(self, src, tgt):
	inst_copy_fun(self, src, tgt)
	if self.generator.bld.options.STRIP and getattr(self.generator, 'link_task', None) and self.generator.link_task.outputs[0] in self.inputs:
		self.generator.bld.cmd_and_log(self.generator.bld.env.STRIP + [tgt], quiet=Context.BOTH)
inst_copy_fun = Build.inst.copy_fun
Build.inst.copy_fun = copy_fun

def build(bld):
	store_path = os.path.join(bld.bldnode.abspath(), 'options.py')
	store_data = ConfigSet.ConfigSet()
	options = vars(bld.options)
	store_data.load(store_path)
	for o in options:
		if options[o]: store_data['OPTIONS'][o] = options[o]
	bld.options = optparse.Values(store_data['OPTIONS'])
	bld.load_envs()
	for name in PROJECTS:
		saveenv = bld.env
		bld.env = bld.all_envs[name]
		bld.recurse(name)
		bld.env = saveenv
