#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	sources = [
		File	(['bitmap.cpp']),
		File	(['colorconversion.cpp']),
		File	(['floatbitmap.cpp']),
		File	(['floatbitmap2.cpp']),
		File	(['floatbitmap3.cpp']),
		File	(['floatbitmap4.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['floatbitmap_bilateralfilter.cpp']),
		File	(['floatcubemap.cpp']),
		File	(['imageformat.cpp']),
		File	(['psd.cpp']),
		File	(['psheet.cpp']),
		File	(['resample.cpp']),
		File	(['tgaloader.cpp']),
		File	(['texturepacker.cpp']),
		File	(['tgawriter.cpp'])
	]

	includes = []

	libs = []

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.stlib(
		target   = 'bitmap',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
