#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	conf.env.append_unique('DEFINES', ['MDLCACHE_DLL_EXPORT'])
 
def build(bld):
	sources = [
		File	(['datacache.cpp']),
		File	(['mdlcache.cpp']),
		File	(['mdlcombine.cpp']),
		File	(['vtfcombine.cpp']),
		File	(['resourceaccesscontrol.cpp']),
		File	(['precachesystem.cpp']),
		File	(['../public/studio.cpp']),
		File	(['../public/studio_virtualmodel.cpp']),
		File	(['../common/studiobyteswap.cpp']),
		File	(['../utils/common/datalinker.cpp']),
		File	(['../public/tier0/memoverride.cpp'])
	]

	includes = []

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'tier3',
		'interfaces',
		'vstdlib',
		'mathlib'
	]

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.shlib(
		target   = 'datacache',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		install_path = bld.env.BINDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
