#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	conf.env.append_unique('DEFINES', ['NO_STRING_T'])
 
def build(bld):
	sources = [
		File	(['inputstacksystem.cpp']),
		File	(['inputsystem.cpp']),
		File	(['joystick.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['joystick_osx.cpp'], lambda x: x.env.DEST_OS == 'darwin'),
		File	(['joystick_linux.cpp'], lambda x: x.env.DEST_OS == 'linux'),
		File	(['steamcontroller.cpp']),
		File	(['key_translation.cpp']),
		File	(['xcontroller.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['../common/platforminputdevice.cpp']),
		File	(['../public/tier0/memoverride.cpp'])
	]

	includes = []

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'mathlib',
		'steam_api',
		'SDL2'
	]

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.shlib(
		target   = 'inputsystem',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		install_path = bld.env.BINDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
