#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	conf.env.append_unique('DEFINES', ['MATHLIB_EXTENDED_LIB'])

def build(bld):
	sources = [
		File	(['../disjoint_set_forest.cpp']),
		File	(['../dynamictree.cpp']),
		File	(['../eigen.cpp']),
		File	(['../simdvectormatrix.cpp']),
		File	(['../femodel.cpp']),
		File	(['../femodelbuilder.cpp']),
		File	(['../feagglomerator.cpp']),
		File	(['../svd.cpp']),
		File	(['../transform.cpp']),
		File	(['../femodeldesc.cpp']),
		File	(['../softbody.cpp']),
		File	(['../softbodyenvironment.cpp'])
	]

	includes = [
		'../../public/mathlib'
	]

	libs = []

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.stlib(
		target   = 'mathlib_extended',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
