#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	if bld.options.NDK:
		return

	sources = [
		File	(['main.cpp']),
		File	(['launcher_main.rc'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['../launcher/res/launcher.ico'], lambda x: x.env.DEST_OS == 'win32')
	]

	includes = []

	libs = []

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld(
		target   = 'csgo_launcher',
		features = 'c cxx cxxprogram',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		install_path = bld.env.PREFIX,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
