#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	conf.env.append_unique('DEFINES', ['FILESYSTEM_STDIO_EXPORTS'])
 
def build(bld):
	sources = [
		File	(['basefilesystem.cpp']),
		File	(['packfile.cpp']),
		File	(['filetracker.cpp']),
		File	(['filesystem_async.cpp']),
		File	(['filesystem_stdio.cpp']),
		File	(['../public/kevvaluescompiler.cpp']),
		File	(['../public/zip_utils.cpp']),
		File	(['QueuedLoader.cpp']),
		File	(['linux_support.cpp'], lambda x: x.env.DEST_OS != 'win32'),
		File	(['../public/tier0/memoverride.cpp'])
	]

	includes = []

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'vpklib'
	]

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.shlib(
		target   = 'filesystem_stdio',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		install_path = bld.env.BINDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
