#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	sources = [
		File	(['AppSystemGroup.cpp']),
		File	(['../public/filesystem_init.cpp']),
		File	(['VguiMatSysApp.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['matsysapp.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['WinApp.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['posixapp.cpp'], lambda x: x.env.DEST_OS != 'win32'),
		File	(['sdlmgr.cpp'], lambda x: x.env.DEST_OS == 'linux'),
		File	(['cocoamgr.mm'], lambda x: x.env.DEST_OS == 'darwin')
	]

	includes = []

	libs = []

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.stlib(
		target   = 'appframework',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
