#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	sources = [
		File	(['assetpicker.cpp']),
		File	(['baseassetpicker.cpp']),
		File	(['colorpickerpanel.cpp']),
		File	(['curveeditorpanel.cpp']),
		File	(['gamefiletreeview.cpp']),
		File	(['manipulator.cpp']),
		File	(['matsyscontrols.cpp']),
		File	(['mdlpanel.cpp']),
		File	(['mdlpicker.cpp']),
		File	(['mdlsequencepicker.cpp']),
		File	(['picker.cpp']),
		File	(['potterywheelpanel.cpp']),
		File	(['proceduraltexturepanel.cpp']),
		File	(['QCGenerator.cpp']),
		File	(['sequencepicker.cpp']),
		File	(['sheetsequencepanel.cpp']),
		File	(['tgapicker.cpp']),
		File	(['tgapreviewpanel.cpp']),
		File	(['vmtpicker.cpp']),
		File	(['vmtpreviewpanel.cpp']),
		File	(['vtfpicker.cpp']),
		File	(['vtfpreviewpanel.cpp']),
		File	(['vmtpanel.cpp'])
	]

	includes = []

	libs = []

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.stlib(
		target   = 'matsys_controls',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
