#!/usr/bin/env python
# modified from FWGS/xash3d-fwgs

from waflib import Build, Context, Logs
from waflib.Tools import waf_unit_test
import sys, os

default_prefix = '../game'

PROJECTS = [
	'tier0',
	'tier1',
	'tier2',
	'tier3',
	'interfaces',
	'vstdlib',
	'mathlib',
	'mathlib/extended'
]

def options(opt):
	opt.load('compiler_c compiler_cxx waf_unit_test')

	grp = opt.add_option_group('Common options')

	grp.add_option('--64bits', action = 'store_true', dest = 'PLATFORM_64BITS', default = False,
		help = 'build for 64bits platform [default: %default]')

	grp.add_option('--cfg', action = 'store', dest = 'CFG', default = 'release',
		help = 'build types [default: %default]')

	grp.add_option('--ccache', action = 'store_true', dest = 'CCACHE', default = False,
		help = 'build with ccache [default: %default]')

	grp.add_option('--strip', action = 'store_true', dest = 'STRIP', default = False,
		help = 'strip libs\' additional info [default: %default]')

	grp.add_option('--ndk', action = 'store_true', dest = 'NDK', default = False,
		help = 'build with android ndk [default: %default]')

def configure(conf):
	conf.load('compiler_c compiler_cxx')

	if conf.options.CCACHE:
		conf.find_program('ccache', var='CCACHE')
	if conf.options.STRIP:
		conf.find_program('strip', var='STRIP')

	defines = ['CSTRIKE_REL_BUILD=1','RAD_TELEMETRY_DISABLED','CSTRIKE15','VERSION_SAFE_STEAM_API_INTERFACES']

	if conf.env.DEST_OS in ['linux','android']:
		cflags = ['-fPIC','-std=c11','-pthread']
		cxxflags = ['-fPIC','-std=c++11','-pthread']
		linkflags = ['-pthread','-ldl','-no-canonical-prefixes','-Wl,--no-warn-mismatch']
		defines += ['GNUC','_DLL_EXT=.so','_LINUX','LINUX','_POSIX','POSIX','GL_GLEXT_PROTOTYPES','DX_TO_GL_ABSTRACTION','USE_SDL']
		warnings = ['-Wall']

		if conf.env.CC_NAME == 'gcc':
			warnings += ['-fdiagnostics-color=always']
			defines += ['COMPILER_GCC']
		elif conf.env.CC_NAME == 'clang':
			warnings += ['-fcolor-diagnostics']
			defines += ['COMPILER_CLANG']

		ndkflags = []
		march = []

		if conf.options.NDK:
			if 'NDK_PATH' in os.environ:
				ndk_path = os.environ.get('NDK_PATH')
			else:
				conf.fatal('Set NDK_PATH environment variable pointing to the root of Android NDK!')

			if conf.options.PLATFORM_64BITS:
				conf.env.DEST_CPU = 'aarch64'
				conf.env.CC = conf.env.LINK_CXX = conf.env.LINK_CC = [ndk_path + '/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc']
				conf.env.CXX = [ndk_path + '/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++']
				ndkflags += ['--sysroot=' + ndk_path + '/platforms/android-21/arch-arm64','-I' + ndk_path + '/sources/android/support/include','-I' + ndk_path + '/sources/cxx-stl/gnu-libstdc++/4.9/include','-I' + ndk_path + '/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include','-L' + ndk_path + '/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a','-L' + ndk_path + '/sources/android/support/libs/arm64-v8a']
				march += ['-march=armv8-a','-mtune=cortex-a53','-mcpu=cortex-a53']
				linkflags += ['-lm']
			else:
				conf.env.DEST_CPU = 'arm'
				ndk_path = os.environ.get('NDK_PATH')
				conf.env.CC = conf.env.LINK_CXX = conf.env.LINK_CC = [ndk_path + '/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc']
				conf.env.CXX = [ndk_path + '/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++']
				ndkflags += ['--sysroot=' + ndk_path + '/platforms/android-21/arch-arm','-I' + ndk_path + '/sources/android/support/include','-I' + ndk_path + '/sources/cxx-stl/gnu-libstdc++/4.9/include','-I' + ndk_path + '/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a-hard/include','-L' + ndk_path + '/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a-hard','-L' + ndk_path + '/sources/android/support/libs/armeabi-v7a']
				march += ['-march=armv7-a','-mtune=cortex-a15','-mthumb','-mfloat-abi=hard','-mfpu=neon','-mcpu=cortex-a9','-mvectorize-with-neon-quad']
				linkflags += ['-lm_hard']
			linkflags += ['-lgnustl_static','-landroid_support']
			defines += ['ANDROID']
			out, err = conf.cmd_and_log(conf.env.CC + ['-dM', '-E', '-'], output=0, input='\n'.encode(), env=conf.env.env)

		if not conf.env.CC_NAME == 'clang' and not conf.options.CFG == 'asan':
			linkflags += ['-Wl,--no-undefined']
		if conf.env.CC_NAME == 'clang':
			linkflags += ['-stdlib=libstdc++']

		if conf.options.CFG == 'debug':
			cflags += ['-O0','-g3']
			cxxflags += ['-O0','-g3']
			defines += ['DEBUG=1','_DEBUG=1']
		elif conf.options.CFG == 'release':
			cflags += ['-O3']
			cxxflags += ['-O3']
		elif conf.options.CFG == 'asan':
			cflags += ['-O0','-g','-fsanitize=address']
			cxxflags += ['-O0','-g','-fsanitize=address']
			linkflags += ['-fsanitize=address']
		else:
			conf.fatal('cfg not found')

		if conf.options.CFG != 'debug':
			defines += ['NDEBUG=1']

		if conf.options.PLATFORM_64BITS:
			if conf.env.DEST_CPU == 'x86_64':
				march += ['-march=nocona','-mtune=core2','-mfpmath=sse']
			defines += ['PLATFORM_64BITS']
		elif conf.env.DEST_CPU in ['x86','x86_64'] and not conf.options.PLATFORM_64BITS:
			march += ['-m32','-march=prescott','-mtune=core2','-mfpmath=sse']

		conf.env.append_unique('CFLAGS', march + cflags + warnings + ndkflags)
		conf.env.append_unique('CXXFLAGS', march + cxxflags + warnings + ndkflags)
		conf.env.append_unique('LINKFLAGS', march + linkflags + ndkflags)
		conf.env.append_unique('DEFINES', defines)

	includes = [
		os.path.abspath('common'),
		os.path.abspath('public'),
		os.path.abspath('public/tier0'),
		os.path.abspath('public/tier1'),
		os.path.abspath('thirdparty/SDL2')
	]
	conf.env.append_unique('INCLUDES', includes)

	if conf.options.CCACHE:
		conf.env.CC = conf.env.CCACHE + conf.env.CC
		conf.env.CXX = conf.env.CCACHE + conf.env.CXX

	conf.check_cc(cflags=cflags, linkflags=linkflags, msg='Checking for required C flags')
	conf.check_cxx(cxxflags=cxxflags, linkflags=linkflags, msg='Checking for required C++ flags')

	for name in PROJECTS:	
		depth_push(name)
		saveenv = conf.env
		conf.setenv(name, conf.env)
		conf.env.ENVNAME = name
		conf.recurse(name)
		conf.setenv('')
		conf.env = saveenv
		depth_pop()

DEPTH = ''
def depth_push(path):
	global DEPTH
	DEPTH = os.path.join(DEPTH, path)
def depth_pop():
	global DEPTH
	DEPTH = os.path.dirname(DEPTH)

# modified from waf/playground/strip/strip_on_install.py
def copy_fun(self, src, tgt):
	inst_copy_fun(self, src, tgt)
	if self.generator.bld.options.STRIP and getattr(self.generator, 'link_task', None) and self.generator.link_task.outputs[0] in self.inputs:
		self.generator.bld.cmd_and_log(self.generator.bld.env.STRIP + [tgt], quiet=Context.BOTH)
inst_copy_fun = Build.inst.copy_fun
Build.inst.copy_fun = copy_fun

def build(bld):
	bld.load_envs()
	for name in PROJECTS:
		saveenv = bld.env
		bld.env = bld.all_envs[name]
		bld.recurse(name)
		bld.env = saveenv
