#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	sources = [
		File	(['device_dsound.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['device_xaudio2.cpp'], lambda x: x.env.DEST_OS == 'win32'),
		File	(['device_sdl.cpp'], lambda x: x.env.DEST_OS != 'win32'),
		File	(['device_null.cpp']),
		File	(['mix.cpp']),
		File	(['simple_filter.cpp']),
		File	(['windows_audio.cpp'], lambda x: x.env.DEST_OS == 'win32')
	]

	includes = []

	libs = []

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.stlib(
		target   = 'soundsystem_lowlevel',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
