#! /usr/bin/env python

class File:
	def __init__(self, name, fnFilter = None):
		self.name = name
		self.fnFilter = fnFilter
	def is_enabled(self, ctx):
		if self.fnFilter:
			return self.fnFilter(ctx)
		return True

def options(opt):
	pass

def configure(conf):
	conf.env.append_unique('DEFINES', ['JPH_DISABLE_CUSTOM_ALLOCATOR','JPH_DEBUG_RENDERER'])
 
def build(bld):
	sources = [
		File	(['../public/collisionutils.cpp']),
		File	(['../public/filesystem_helpers.cpp']),
		File	(['vjolt_collide.cpp']),
		File	(['vjolt_collide_trace.cpp']),
		File	(['vjolt_constraints.cpp']),
		File	(['vjolt_controller_fluid.cpp']),
		File	(['vjolt_controller_motion.cpp']),
		File	(['vjolt_controller_player.cpp']),
		File	(['vjolt_controller_vehicle.cpp']),
		File	(['vjolt_controller_shadow.cpp']),
		File	(['vjolt_debugrender.cpp']),
		File	(['vjolt_environment.cpp']),
		File	(['vjolt_friction.cpp']),
		File	(['vjolt_interface.cpp']),
		File	(['vjolt_keyvalues_schema.cpp']),
		File	(['vjolt_object.cpp']),
		File	(['vjolt_objectpairhash.cpp']),
		File	(['vjolt_parse.cpp']),
		File	(['vjolt_querymodel.cpp']),
		File	(['vjolt_surfaceprops.cpp']),
		File	(['../public/tier0/memoverride.cpp'])
	]

	includes = [
		'../thirdparty/joltphysics'
	]

	libs = [
		'tier0',
		'tier1',
		'tier2',
		'interfaces',
		'vstdlib',
		'mathlib',
		'jolt'
	]

	sources_platform = []
	for i in sources:
		if not i.is_enabled(bld):
			continue
		sources_platform += i.name

	bld.shlib(
		target   = 'vphysics',
		features = 'c cxx',
		source   = sources_platform,
		includes = includes,
		use      = libs,
		install_path = bld.env.BINDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM
	)
